language: php

php:
  - 7.1

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - ./tests/setup.sh
  - composer validate

install:
  - composer --prefer-dist install

script:
  - ./test
