language: php

php:
  - 7.0
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - ./tests/setup.sh

install:
  - composer install
  - composer validate

# Install phan separately because the tolerant-php-parser version may be behind.
script:
  - composer.phar create-project phan/phan=0.10.4 ~/phan-install; ~/phan-install/phan
  - ./test

branches:
  only:
  - master
