language: php

php:
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - ./tests/setup.sh

# TODO: reintroduce composer validate after phan 0.10.0 is released
install:
  - composer install

script:
  - ./vendor/bin/phan
  - ./test

branches:
  only:
  - master
