language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

dist: xenial

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/phan-ast/build

before_install:
  - ./tests/setup.sh

install:
  - composer install
  - composer validate

# Install phan separately because the tolerant-php-parser version may be behind.
script:
  - composer create-project phan/phan=1.2.1 ~/phan-install; ~/phan-install/phan
  - ./test

branches:
  only:
  - master
